// <auto-generated />
using System;
using Asus_rest.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Asus_rest.Migrations
{
    [DbContext(typeof(AsusContext))]
    partial class AsusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Asus_rest.Domain.Kupac", b =>
                {
                    b.Property<string>("PiB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NazivKupca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ulicaIBroj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PiB");

                    b.ToTable("Kupci");
                });

            modelBuilder.Entity("Asus_rest.Domain.OdgovornoLice", b =>
                {
                    b.Property<int>("SifraRadnika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImePrezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrzisteID")
                        .HasColumnType("int");

                    b.HasKey("SifraRadnika");

                    b.HasIndex("TrzisteID");

                    b.ToTable("OdgovornaLica");
                });

            modelBuilder.Entity("Asus_rest.Domain.Porudzbenicca", b =>
                {
                    b.Property<int>("PorudzbeniccaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumPor")
                        .HasColumnType("datetime2");

                    b.Property<string>("KupacPiB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("OdgovornoLiceSifraRadnika")
                        .HasColumnType("int");

                    b.Property<string>("PiB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SifraRadnika")
                        .HasColumnType("int");

                    b.HasKey("PorudzbeniccaID");

                    b.HasIndex("KupacPiB");

                    b.HasIndex("OdgovornoLiceSifraRadnika");

                    b.ToTable("Porudzbenicce");
                });

            modelBuilder.Entity("Asus_rest.Domain.Proizvod", b =>
                {
                    b.Property<int>("SifraProizvoda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazivModela")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SifraProizvoda");

                    b.ToTable("Proizvodi");
                });

            modelBuilder.Entity("Asus_rest.Domain.StavkaPorudzbenicce", b =>
                {
                    b.Property<int>("stavkaPorudzbenicceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProizvodSifraProizvoda")
                        .HasColumnType("int");

                    b.Property<int>("SifraProizvoda")
                        .HasColumnType("int");

                    b.Property<int>("kolicina")
                        .HasColumnType("int");

                    b.Property<int>("porudzbenicaID")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("stavkaPorudzbenicceID");

                    b.HasIndex("ProizvodSifraProizvoda");

                    b.HasIndex("porudzbenicaID");

                    b.ToTable("StavkePorudzbenicce");
                });

            modelBuilder.Entity("Asus_rest.Domain.Trziste", b =>
                {
                    b.Property<int>("SifraTrzista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SifraTrzista");

                    b.ToTable("Trzista");
                });

            modelBuilder.Entity("Asus_rest.Domain.OdgovornoLice", b =>
                {
                    b.HasOne("Asus_rest.Domain.Trziste", "Trziste")
                        .WithMany()
                        .HasForeignKey("TrzisteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trziste");
                });

            modelBuilder.Entity("Asus_rest.Domain.Porudzbenicca", b =>
                {
                    b.HasOne("Asus_rest.Domain.Kupac", "Kupac")
                        .WithMany()
                        .HasForeignKey("KupacPiB");

                    b.HasOne("Asus_rest.Domain.OdgovornoLice", "OdgovornoLice")
                        .WithMany()
                        .HasForeignKey("OdgovornoLiceSifraRadnika");

                    b.Navigation("Kupac");

                    b.Navigation("OdgovornoLice");
                });

            modelBuilder.Entity("Asus_rest.Domain.StavkaPorudzbenicce", b =>
                {
                    b.HasOne("Asus_rest.Domain.Proizvod", "Proizvod")
                        .WithMany()
                        .HasForeignKey("ProizvodSifraProizvoda");

                    b.HasOne("Asus_rest.Domain.Porudzbenicca", "porudzbenica")
                        .WithMany("StavkePorudzbenice")
                        .HasForeignKey("porudzbenicaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("porudzbenica");

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("Asus_rest.Domain.Porudzbenicca", b =>
                {
                    b.Navigation("StavkePorudzbenice");
                });
#pragma warning restore 612, 618
        }
    }
}
